
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS tracks CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS artists_tags CASCADE;

CREATE TABLE fleets (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE ships (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  date_built DATETIME NOT NULL,
  fleet_id INTEGER NOT NULL REFERENCES fleets(id) 
);

CREATE TABLE sailors (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  date_of_birth DATE NOT NULL,
)

CREATE TABLE tours (
  id SERIAL PRIMARY KEY NOT NULL,
  shipid INTEGER NOT NULL REFERENCES ships(id),
  sailorid INTEGER NOT NULL REFERENCES sailors(id),
  duty VARCHAR(50) NOT NULL,
  tour_start DATETIME NOT NULL,
  tour_end DATETIME NOT NULL,
  rank varchar(30)
);